### ISSUE TITLE
Mauvais nom de dossier (Wrong directory name)

### ISSUE THREAD

**Issue by ChrisDu17** [PluginsOCSInventory-NG/runningProcess#2]
En installant le plugin, le nom du dossier "/etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/RunningProcess" était incorrect.
RunningProcess à la place de Runningprocess

Apache a refusé de redémarrer aujourd'hui à cause de ce module.

En changeant simplement le P majuscule en p minuscule dans le nom du dossier, le serveur apache a redémarré normalement.

Je crois qu'il y a une erreur dans le script d'installation concernant la création de ce dossier.

When the plugin is installed, the directory "/etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/RunningProcess" was not good.
RunningProcess is the directory name, but Runningprocess must be.

Apache don't start today because of this module.

When the P is changed in p int the directory name, apache start well.

I think there is mistake in the installation script for the directory creation.
(sorry for this bad english)

**Comment by MyTheValentinus** [comment]
Bonjour @ChrisDu17,
Le soucis vient d'être résolu, j'ai mis en ligne une nouvelle release.
Merci pour le retour
A bientôt
